name: Codecov coverage computation
on: 
  push:
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - name: Remove unused Docker images
      run: docker system prune -af
    - name: Clean up temporary files
      run: sudo rm -rf /tmp/*
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Generate coverage report
      run: |
        pip install .
        pip install pytest
        pip install pytest-cov
        pytest --cov=multivae ./ --cov-report=xml --runslow
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true